/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package uzhnu.edu.bai.dialog

class Library {
    fun someLibraryMethod(): Boolean {
        // dummy comment
        return true
    }
}
